source 'https://github.com/CocoaPods/Specs.git'

target 'TFQImageScollView', :exclusive => true do
    pod "TFQImageScollView", :path => "../"
    pod "SDWebImage"
end

target 'Tests', :exclusive => true do
    pod "TFQImageScollView", :path => "../"
  pod 'Kiwi'
end
