source 'https://github.com/CocoaPods/Specs.git'

target 'TFQImageScrollView', :exclusive => true do
    pod "TFQImageScrollView", :path => "../"
    pod "SDWebImage"
end

target 'Tests', :exclusive => true do

  
end
